name: ml-utilities
channels:
  - apple
dependencies:
  - pip=23.1
  - python=3.10
  - jupyter=1.0.0
  - keras-tuner=1.3.5
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - pandas=2.0.0
  - shap=0.41.0
  - pip:
    - tensorflow-macos==2.12.0
    - tensorflow-metal==0.8.0
    - tensorflow-hub==0.13.0